# Generated by Django 5.0.4 on 2024-04-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=200)),
                ('positions', models.CharField(max_length=200)),
                ('party', models.CharField(max_length=200)),
                ('block', models.CharField(choices=[('Block A', 'Block A'), ('Block B', 'Block B'), ('Block C', 'Block C'), ('Block D', 'Block D'), ('Block E', 'Block E'), ('Block F', 'Block F')], default='BLOCK A', max_length=50)),
                ('nationality', models.CharField(default='Liberian', max_length=200)),
                ('photo', models.ImageField(blank=True, default='image.jpg', upload_to='photos/candidates')),
            ],
        ),
    ]
