# Generated by Django 5.0.4 on 2024-04-21 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='photos/members')),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.block')),
            ],
        ),
    ]
